version: 2

sources: 
  - name: staging
    # database: mage-demo-412904
    database: "{{ env_var('GCP_PROJECT_ID') }}"
     # For postgres:
      #database: production
    # schema: us_accidents_2016_2023
    schema: "{{ env_var('DBT_DATASET_BQ') }}" 

      # loaded_at_field: record_loaded_at
    tables:
      - name: accidents_data
         # freshness:
           # error_after: {count: 6, period: hour}

models:
    - name: stg_accidents_data
      description: >
        Source URL : https://smoosavi.org/datasets/us_accidents
        This is a countrywide traffic accident dataset, which covers 49 states of the United States. 
        The data is continuously being collected from February 2016, using several data providers, including 
        multiple APIs that provide streaming traffic event data. These APIs broadcast traffic events captured 
        by a variety of entities, such as the US and state departments of transportation, law enforcement 
        agencies, traffic cameras, and traffic sensors within the road-networks. 
        Currently, there are about 7.73 million accident records in this dataset captured until March 2023.
        Check the below descriptions for more detailed information. 
      columns:
          - name: surrogate_accident_id
            data_type: string
            description: ""
            tests:
              - not_null:
                  severity: warn
              - unique:
                  severity: warn

          - name: id
            data_type: string
            description: This is a unique identifier of the accident record.
            tests:
                - unique:
                    severity: warn
                - not_null:
                    severity: warn
          - name: severity 
            data_type: int64
            description: > 
                Shows the severity of the accident, a number between 1 and 4, 
                where 1 indicates the least impact on traffic 
                (i.e., short delay as a result of the accident) and
                4 indicates a significant impact on traffic (i.e., long delay).
            tests:
                - not_null:
                    severity: warn
                - accepted_values:
                    values: "{{ var('severity_codes') }}"
                    severity: warn
                    quote: false
          - name: start_time 
            data_type: timestamp
            description: Shows start time of the accident in local time zone.
            tests:
              - not_null:
                  severity: warn
          - name: end_time 
            data_type: timestamp
            description: >
                Shows end time of the accident in local time zone.
                End time here refers to when the impact of accident on traffic flow was dismissed.
            tests:
                - not_null:
                    severity: warn
          - name: start_lat 
            data_type: numeric
            description: Shows latitude in GPS coordinate of the start point.
            tests:
                - not_null:
                    severity: warn
          - name: start_lng 
            data_type: numeric
            description: Shows longitude in GPS coordinate of the start point.
            tests:
                  - not_null:
                      severity: warn
          - name: end_lat 
            data_type: numeric 
            description: Shows latitude in GPS coordinate of the end point.
          - name: end_lng 
            data_type: numeric
            description: Shows longitude in GPS coordinate of the end point.
          - name: distance_miles
            data_type: numeric
            description: The length of the road extent affected by the accident.
            tests:
                  - not_null:
                      severity: warn
          - name: description
            data_type: string
            description: Shows natural language description of the accident.
          - name: street
            data_type: string
            description: Shows the street name in address field.
          - name: city
            data_type: string
            description: Shows the city in address field.
          - name: county
            data_type: string
            description: 	Shows the country in address field.
          - name: state
            data_type: string
            description: Shows the state in address field.
            tests:
              - relationships:
                    to: ref('us_states_lookup')
                    field: Abbreviation
                    severity: warn
          - name: zipcode
            data_type: string
            description: Shows the zipcode in address field.
          - name: country
            data_type: string
            description: Shows the country in address field.
          - name: timezone
            data_type: string
            description: Shows timezone based on the location of the accident (eastern, central, etc.).
          - name: airport_Code
            data_type: string
            description: Denotes an airport-based weather station which is the closest one to location of the accident.
          - name: weather_timestamp
            data_type: timestamp
            description: Shows the time-stamp of weather observation record (in local time).	
          - name: temperature_f
            data_type: numeric
            description: Shows the temperature (in Fahrenheit).
          - name: wind_chill_f
            data_type: numeric
            description: Shows the wind chill (in Fahrenheit).
          - name: humidity_perc
            data_type: numeric
            description: Shows the humidity (in percentage).
          - name: pressure_inches
            data_type: numeric
            description: Shows the air pressure (in inches).
          - name: visibility_miles
            data_type: numeric
            description: Shows visibility (in miles).
          - name: wind_direction
            data_type: string
            description: Shows wind direction.
          - name: wind_speed_mph
            data_type: numeric
            description: Shows wind speed (in miles per hour).
          - name: precipitation_inches
            data_type: numeric
            description: Shows precipitation amount in inches, if there is any.
          - name: weather_condition
            data_type: string
            description: Shows the weather condition (rain, snow, thunderstorm, fog, etc.)
          - name: amenity
            data_type: boolean
            description: A POI annotation which indicates presence of amenity in a nearby location.
            tests:
                - not_null:
                    severity: warn
          - name: bump
            data_type: boolean
            description: A POI annotation which indicates presence of speed bump or hump in a nearby location.
            tests:
                - not_null:
                    severity: warn
          - name: crossing
            data_type: boolean
            description: A POI annotation which indicates presence of crossing in a nearby location.
            tests:
                - not_null:
                    severity: warn
          - name: give_way
            data_type: boolean
            description: A POI annotation which indicates presence of give_way in a nearby location.
            tests:
                - not_null:
                    severity: warn
          - name: junction
            data_type: boolean
            description: A POI annotation which indicates presence of junction in a nearby location.	
            tests:
                - not_null:
                    severity: warn
          - name: no_exit
            data_type: boolean
            description: A POI annotation which indicates presence of no_exit in a nearby location.
            tests:
                - not_null:
                    severity: warn
          - name: railway
            data_type: boolean
            description: A POI annotation which indicates presence of railway in a nearby location.
            tests:
                - not_null:
                    severity: warn
          - name: roundabout
            data_type: boolean
            description: A POI annotation which indicates presence of roundabout in a nearby location.	
            tests:
                - not_null:
                    severity: warn
          - name: station
            data_type: boolean
            description: A POI annotation which indicates presence of station in a nearby location.
            tests:
                - not_null:
                    severity: warn
          - name: stop
            data_type: boolean
            description: A POI annotation which indicates presence of stop in a nearby location.
            tests:
                - not_null:
                    severity: warn
          - name: traffic_calming
            data_type: boolean
            description: A POI annotation which indicates presence of traffic_calming in a nearby location.	
            tests:
                - not_null:
                    severity: warn
          - name: traffic_signal
            data_type: boolean
            description: A POI annotation which indicates presence of traffic_signal in a nearby loction.
            tests:
                - not_null:
                    severity: warn
          - name: turning_loop
            data_type: boolean
            description: A POI annotation which indicates presence of turning_loop in a nearby location.
            tests:
                - not_null:
                    severity: warn
          - name: sunrise_sunset
            data_type: string
            description: Shows the period of day (i.e. day or night) based on sunrise/sunset.
          - name: civil_twilight
            data_type: string
            description: Shows the period of day (i.e. day or night) based on civil twilight.
          - name: nautical_twilight
            description: Shows the period of day (i.e. day or night) based on nautical twilight.
          - name: astronomical_twilight
            data_type: string
            description: Shows the period of day (i.e. day or night) based on astronomical twilight.
          - name: start_date
            data_type: date
            description: Shows start date of the accident in local time zone.
            tests:
                - not_null:
                    severity: warn
          - name: end_date
            data_type: date
            description: Shows end time of the accident in local time zone. End time here refers to when the impact of accident on traffic flow was dismissed.
            tests:
                - not_null:
                    severity: warn